# Site settings
title: "Ian Qiu's blog"
email: qiuyiyi2006@163.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎各位
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ian-qiu

# Build settings
markdown: kramdown
timezone: Asia/Shanghai
highlighter: pygments
